version: "3.9"

services:
    talenavi_app:
        build:
            context: .
            dockerfile: docker/Dockerfile.app
        container_name: talenavi_app
        volumes:
            - ./:/var/www/talenavi_app
            - ./public:/var/www/talenavi_app/public
            - ./storage:/var/www/talenavi_app/storage
            - ./bootstrap/cache:/var/www/talenavi_app/bootstrap/cache
        # depends_on:
        #     - talenavi_redis
        networks:
            - talenavi_network

    talenavi_nginx:
        build:
            context: .
            dockerfile: docker/Dockerfile.nginx
        container_name: talenavi_nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/talenavi_app
            - ./public:/var/www/talenavi_app/public
            - ./storage:/var/www/talenavi_app/storage
            - ./bootstrap/cache:/var/www/talenavi_app/bootstrap/cache
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - talenavi_app
        networks:
            - talenavi_network

    # talenavi_redis:
    #     image: redis:latest
    #     container_name: talenavi_redis
    #     volumes:
    #         - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    #     networks:
    #         - talenavi_network

    # talenavi_postgres:
    #     image: postgres:17
    #     container_name: talenavi_postgres
    #     ports:
    #     - "5432:5432"
    #     environment:
    #         POSTGRES_DB: talenavi
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: 1234
    #     volumes:
    #     - ./docker/postgres_data:/var/lib/postgresql/data
    #     networks:
    #     - talenavi_network

#   talenavi_node:
#     build:
#       context: .
#       dockerfile: docker/Dockerfile.node
#     container_name: talenavi_node
#     ports:
#       - "5173:5173"
#     working_dir: /var/www/talenavi_app
#     volumes:
#       - ./:/var/www/talenavi_app
#       - /var/www/talenavi_app/node_modules
#     networks:
#       - talenavi_network

networks:
    talenavi_network:
        driver: bridge
